### ISSUE TITLE
VX0 Not Working

### ISSUE THREAD

**Issue by race19991** [Atla55/Android-Tiers-Core#1]
When I install a VX0 chip on  a colonist or a prisoner he do not get the "no host connected" status and i cannot controll him throught skymind

**Comment by AmsTaFFix** [comment]
i didn't get that issue, and i don't think that mod can correctly work with VX0 in prisoner. But about VX0 in colonist, can you you attach screenshots, logs, list of mods, maybe a save or a scenario how to reproduce this bug

**Comment by aRandomKiwi** [comment]
Should be fixed with the latest 3.0.0RC rev5 update.
