### ISSUE TITLE
Pawns randomly becoming surrogates

### ISSUE THREAD

**Issue by KingAbyx** [Atla55/Android-Tiers-Core#10]
One of my colonists and two wild men just got the "No host connected" health status, without having a chip installed and without me doing anything.
Version 3.0.0RC
Log: https://gist.github.com/1fbfd7fa16defc40bc33e0e4b37abf86

**Comment by aRandomKiwi** [comment]
Should be fixed with the latest 3.0.0RC rev2 update :
https://github.com/Atla55/Android-Tiers-Core/releases/tag/3.0.0.2

Thanks to try and check if it fix your issue.
