### ISSUE TITLE
PrisonLabor patches

### ISSUE THREAD

**Issue by Hazzer** [Atla55/Android-Tiers-Core#11]
Hey, just checked prison labors compatibility patches and wonder if they are still necessary.

Some time ago, I added some improvements for WorkTime method to handle pawns without sleep and food needs.
Link: https://github.com/Aviuz/PrisonLabor/blob/3b4a5e126059f07c1e14f40fc1ccb6f4a3d6df94/Source/Core/PrisonLaborUtility.cs
(comment will be removed soon ;) )

Also, need motivation was wrapped with some null checks:
https://github.com/Aviuz/PrisonLabor/blob/86eb55db4b0a7ebdec02af5445a18e9ba6bfcb92/Source/Core/Needs/Need_Motivation.cs

If some changes are still needed, let me know.

**Comment by aRandomKiwi** [comment]
Hi, i made some testing without the patch and it seems to run without issues (null exceptions), so i removed it.
Thanks for the fixes/report.
