### ISSUE TITLE
Surrogates and mind uploaded pawns dont retain the origin pawn psycasts.

### ISSUE THREAD

**Issue by BlocDeNotas** [Atla55/Android-Tiers-Core#22]
As far as i know psycasts should counted as knowledge learned on the pawn so permuting, controling or uploading minds should give psycasts habilities too based on the origin pawn.

**Comment by FGRemastered** [comment]
Psycasts are something that just is stored to the body.

**Comment by BlocDeNotas** [comment]
Mmmh i thought they where skills just like the levels you get on tasks but learned via consumables. Then i close the thread.
