### ISSUE TITLE
Overload Customizability

### ISSUE THREAD

**Issue by DJDANNY123** [Atla55/Android-Tiers-Core#5]
Hey, love the mod, would love to have the overload option have configurable explosions so you can change the size or intensity or even type of the explosion for your robots (likely through the mod settings), is this something you would consider implementing?

**Comment by aRandomKiwi** [comment]
Feature added on the latest 3.0.0RC rev2 update (explosion radius configurable for androids and M7, and explosion type (frag/incendiary).
