### ISSUE TITLE
Settings for skill server speed default to same value for all

### ISSUE THREAD

**Issue by ptyszko** [Atla55/Android-Tiers-Core#7]
**Game Version**: 1.2.2900
**Mod Version**: 2.0.1

**Problem**: Every time I start-up the game, the values *Number of points produced (every 30 seconds) for I-xxx skill servers* resets to an identical value for all 3 tiers

**How to reproduce**: Set skill server speeds to 3 different values, the close and open the game.

[Modlist here](https://github.com/Atla55/Android-Tiers-Core/files/5942537/modlist.txt)

**Comment by aRandomKiwi** [comment]
Fixed with the latest 3.0.0RC update.
